/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package week1;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author macbook
 */
public class GuessTheWordGame extends javax.swing.JFrame {

    int counter = 0;
    int tries = 3;

    String[] Words = {
        "absolute",
        "abstract",
        "academic",
        "accepted",
        "accident",
        "accuracy",
        "accurate",
        "achieved",
        "acquired",
        "activity",
        "actually",
        "addition",
        "adequate",
        "adjacent",
        "adjusted",
        "advanced",
        "advisory",
        "advocate",
        "affected",
        "aircraft",
        "alliance",
        "although",
        "aluminum",
        "analysis",
        "announce",
        "anything",
        "anywhere",
        "apparent",
        "appendix",
        "approach",
        "approval",
        "argument",
        "artistic",
        "assembly",
        "assuming",
        "athletic",
        "attached",
        "attitude",
        "attorney",
        "audience",
        "autonomy",
        "aviation",
        "bachelor",
        "bacteria",
        "baseball",
        "bathroom",
        "becoming",
        "benjamin",
        "birthday",
        "boundary",
        "breaking",
        "breeding",
        "building",
        "bulletin",
        "business",
        "calendar",
        "campaign",
        "capacity",
        "casualty",
        "catching",
        "category",
        "Catholic",
        "cautious",
        "cellular",
        "ceremony",
        "chairman",
        "champion",
        "chemical",
        "children",
        "circular",
        "civilian",
        "clearing",
        "clinical",
        "clothing",
        "collapse",
        "colonial"};

    String[] Guesses = {
        "uoaetbsl",
        "atatcbsr",
        "mdacicae",
        "teadeccp",
        "eiatnccd",
        "auaycccr",
        "auaetccr",
        "viadeche",
        "ruadecqi",
        "iiaytctv",
        "luaylcta",
        "iianoddt",
        "aqaetdeu",
        "eaatndjc",
        "tuadedjs",
        "caadedvn",
        "oiayrdvs",
        "aoaetdvc",
        "teadeffc",
        "acatfirr",
        "niaeclla",
        "uhahglto",
        "nmamului",
        "slasinay",
        "noaecnnu",
        "itagnnyh",
        "ewaernyh",
        "eaatnppr",
        "deaxippn",
        "arahcppo",
        "vralappo",
        "euatnrgm",
        "tiacirts",
        "beaylssm",
        "iuagnssm",
        "tlacithe",
        "haadettc",
        "uiaedttt",
        "noayettr",
        "niaecude",
        "ooaymutn",
        "iaanovit",
        "lhbroace",
        "rtbaiace",
        "aebllasb",
        "ohbmoatr",
        "iobgnecm",
        "mjbniena",
        "dtbyairh",
        "anbyroud",
        "iabgnrek",
        "iebgnred",
        "ilbgnuid",
        "tlbniule",
        "eibssusn",
        "decraaln",
        "ipcngama",
        "iacytapc",
        "lucytasa",
        "iccgnath",
        "oecyratg",
        "lhCciato",
        "otcsuaui",
        "llcraelu",
        "oecynerm",
        "micnahar",
        "imcnohap",
        "cmclahei",
        "rlcnehid",
        "lccrairu",
        "iicnaivl",
        "iacgnler",
        "cnclalii",
        "itcgnloh",
        "plcesola",
        "ioclaoln"};

    /**
     * Creates new form guessingGame
     */
    public GuessTheWordGame() {
        initComponents();
        jLabel5.setText(Guesses[0]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Georgia", 3, 37)); // NOI18N
        jLabel2.setText("Guess the Word");

        jLabel1.setText("Word");

        jLabel3.setText("Your Guess");

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Check");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jButton1)
                                .addGap(61, 61, 61)
                                .addComponent(jButton2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int length = Words.length;
        tries = 3;
        if (counter >= length) {
            JOptionPane.showMessageDialog(rootPane, "No More Guesses Available!");
        } else {
            counter++;
            jLabel5.setText(Guesses[counter]);
            jTextField1.setText("");
            jLabel4.setText("");
            jLabel6.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String guess = jTextField1.getText().trim();
        String correct_word = Words[counter];
        if (guess.equalsIgnoreCase(correct_word)) {
            jLabel4.setText("Correct!");
            jLabel4.setForeground(Color.green);
        } else {
            jLabel4.setText("Olodo!");
            jLabel4.setForeground(Color.red);
            if (tries == 1) {
                JOptionPane.showMessageDialog(rootPane, "You have exhausted your chances!");
                counter++;
                jLabel5.setText(Guesses[counter]);
                jTextField1.setText("");
                jLabel4.setText("");
                jLabel6.setText("");
            }
            else {
                tries--;
                jLabel6.setText("You have "+tries+" left");

            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuessTheWordGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuessTheWordGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuessTheWordGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuessTheWordGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuessTheWordGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
